
AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  Exclude:
    - db/schema.rb
    - db/migrate/**/*
    - node_modules/**/*
    - lib/tasks/auto_annotate_models.rake


Layout/HashAlignment:
  EnforcedColonStyle: table

Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*"

Layout/LineLength:
  Max: 100
  IgnoredPatterns: ['\A#']
  Exclude:
    - bin/bundle
    - config/initializers/devise.rb
    - config/environments/production.rb
    - Gemfile

Metrics/BlockLength:
  Exclude:
    - Guardfile

Metrics/CyclomaticComplexity:
  Exclude:
    - bin/bundle

Metrics/MethodLength:
  Exclude:
    - bin/bundle
    - lib/guard/webpacker.rb

Metrics/PerceivedComplexity:
  Exclude:
    - bin/bundle

Style/AsciiComments:
  Exclude:
    - Gemfile

Style/Documentation:
  Enabled: false

Style/NumericLiterals:
  Enabled: false
