#!/bin/sh

set -e

if [ -z "$INSIDE_CONTAINER" ]; then
  rm -f tmp/pids/server.pid
  sh -c "trap 'docker-compose down' EXIT; docker-compose up"
else
  export RAILS_ENV=development
  bundle check >/dev/null || ./script/bundle_install
  bin/rails db:migrate 2>/dev/null || bin/rails db:setup
  bin/rails server
fi